version: '3.1'
services:
  nginx:
   image: nginx:latest
   restart: always
   volumes: 
     - nginx_volume:/usr/share/nginx/html/vol
  httpd:
   image: httpd:latest
   ports:
     - 81:80
   
volumes:
  nginx_volume:
    driver: local
